const items = [
  "Bagpiper",
  "Bassist",
  "Cellist",
  "Clarinetist",
  "DJ",
  "Drummer",
  "Flutist",
  "Guitarist - Acoustic",
  "Guitarist - Electric",
  "Keyboardist",
  "Oboist",
  "Organist",
  "Pianist",
  "Percussionist",
  "Saxophone",
  "Trumpetist",
  "Violinist",
  "Vocalist - Lead",
  "Vocalist - Backup",
  "Animal handler",
  "Ballet Dancers",
  "Backup Dancers",
  "Aerialists",
  "Balloon Artists",
  "Juggler / Variety",
  "Contortionist",
  "Clown",
  "Flow Arts",
  "Pole Dancers",
  "Magician/Illusionists",
  "Dance Team",
  "Fire Performers",
  "Pyro Technicians",
  "Cyr-Wheel Performer",
  "Stilt Walkers",
  "Usher",
  "Security",
  "Rigger",
  "Living Statue",
  "Choreographer",
  "Sound Designer",
  "Sound Engineer",
  "Fire Marshall",
  "EMT / Paramedic",
  "Lighting Technicians",
  "Stage Hands",
  "Stage Manager",
  "Costume Designers",
  "Makeup Artists",
  "Gaffer",
  "Grip - Key",
  "Grip",
  "Camera Operators",
  "Director",
  "Directors Assistant / DA",
  "Setup/Tear Down",
  "Live Painter",
  "Cyclists",
  "Waffleman",
  "Burlesque",
  "Hand Balancing",
  "Hand-to-Hand",
  "Stage Combat",
  "Stuntman",
  "Character Work",
  "Actor/Actress",
  "Belly Dancer",
  "Renaissance - Combatant",
  "Renaissance - Actor/Actress",
  "Renaissance - Dancer",
  "Mime",
  "Lamp Operator",
  "Makeup Artist",
  "Makeup Artist - Special Effects",
  "Truckers",
  "Operators/Dispatch",
  "Limo",
  "Medical Transport",
  "Taxi Service",
  "Mobile Mechanics",
  "Tinting",
  "Car Wrapping",
  "Mobile Detailing",
  "Food Trucks",
  "Art Director",
  "Creative Director",
  "Drone Operator",
  "Editor",
  "Editor - Retouch Artist",
  "Lighting Technician",
  "Location Manager",
  "Model",
  "Photographer - Assistant",
  "Photographer - Boudoir",
  "Photographer - Commercial / Product",
  "Photographer - Couples",
  "Photographer - Engagement",
  "Photographer - Family",
  "Photographer - Landscape",
  "Photographer - Nature",
  "Photographer - Portrait / Studio",
  "Photographer - Wedding",
  "Production Assistant (PA)",
  "Set Designer",
  "Stylist",
  "Assistant Director",
  "Best Boy / Lighting",
  "Boom Operator",
  "Camera Operator",
  "Casting Director",
  "Cinematographer / Director of Photography",
  "Costume Designer",
  "Dialect Coach",
  "Editor - Colorist",
  "Editor - Sound",
  "Editor - VFX Artist",
  "Foley Artist",
  "Hair Stylist",
  "Photographer",
  "Producer",
  "Production Designer",
  "Prop Master",
  "Seamstress/Tailor",
  "Script Supervisor",
  "Sound Mixer",
  "Stunt - Coordinator",
  "Stunt - Performer",
  "VFX Supervisor",
  "VFX Artist",
  "Wardrobe Supervisor",
  "Officiant - Jewish",
  "Officiant - Christian",
  "Officiant - Muslim",
  "Officiant - Hindu",
  "Officiant - Non-Religious",
  "Officiant - Buddhist",
  "Florists",
  "Caterer",
  "Caterers - Food Trucks",
  "Baker",
  "Wedding Designer",
  "Wedding Decorator",
  "Get-a-way Car/Driver",
  "Wedding Painter",
  "bartender",
  "Ushers",
  "Videographer",
  "Valet",
  "Wedding Coordinator",
  "Musicians",
  "Magicians",
  "Contractor - Carpenter",
  "Contractor - Drywall",
  "Contractor - General",
  "Contractor - HVAC",
  "Contractor - Electrician",
  "Contractor - Plumbers",
  "Contractor - Flooring",
  "Contractor - Painters",
  "Contractor - Roofing",
  "Contractor - Windows",
  "Contractor - Mason",
  "Dog Walker",
  "Dog Trainer",
  "Landscaping",
  "Nanny",
  "House Manager",
  "Cleaning Services",
  "Doula",
  "Midwifes",
  "House Sitter",
];

for (let item of items) {
  // url encode item
  const encodedItem = encodeURIComponent(item);
  console.log(
    `('${item}', 'https://placehold.co/600x400?text=${encodedItem}'),`
  );
}
